permalink: /:categories/:title/
url: "https://jiwan1.github.io/"
full_name: "Saigon Jekyll Theme"
first_name: "Just"
last_name: "Me"
blog_title: "blog"
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "jiwan1"
copyright_year: "2019"
google_analytics_code: ""
aboutme: "I like ramen noodles with cream."

